### ISSUE TITLE
[Bug]: README region code example is incorrect

### ISSUE THREAD

**Issue by Vanilagy** [spatie/holidays#213]
### What happened?

Just like the README says, I tried doing this to get all holidays for Hesse, Germany:
```php
Holidays::for(Germany::make(region: 'DE-HE'), year: $year)->get();
```

But this failed, as the make method doesn't take in named params. Instead, this works:
```php
Holidays::for(Germany::make('DE-HE'), year: $year)->get();
```

### How to reproduce the bug

```php
Germany::make(region: 'DE-HE');
```

### Package Version

1.8

### PHP Version

8.3.0

### Which operating systems does with happen with?

macOS

**Comment by arnebr** [comment]
This true, the ::make function does not allow named parameters there. Some of the countries like Switzerland have set their constructor to `public`  to enable something like `new CountryName(region:'AB-CD')` that will work then. I will make an adjustment PR to reflect it in the README.md thanks for hinting that.


The other option would be to shift each country to a public constructor to initiate each county like new CountryName(region) but this a big PR and @Nielsvanpach needs to decide that
