### ISSUE TITLE
[Bug]: tests failing

### ISSUE THREAD

**Issue by alphaolomi** [spatie/holidays#97]
### What happened?

Most PRs fail due to wrong snapshots

### How to reproduce the bug

Run tests on main branch

### Package Version

Latest

### PHP Version

*8.1

### Notes

Refreshing the snapshots will fix tests.

**Comment by kndrckjvr** [comment]
created a PR for this [fix](https://github.com/spatie/holidays/pull/117)!

**Comment by Nielsvanpach** [comment]
Already fixed
